services:
  db:
    image: mysql:8.0
    container_name: mysql_reservas
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: proyecto_reservas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./init/init.sql:/docker-entrypoint-initdb.d/02-init.sql:ro
    networks:
      - reservas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_reservas
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - reservas-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_reservas
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - reservas-network

  back-reservas-desarrollo:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back-reservas-desarrollo
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install && npm run dev:docker"
    env_file:
      - ./back/.env.docker
    environment:
      NODE_ENV: development
      DOTENV_CONFIG_PATH: /app/.env.docker
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "4000:4000"
    volumes:
      - ./back:/app
      - back_node_modules:/app/node_modules
      - back_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - reservas-network

  front-reservas-desarrollo:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: front-reservas-desarrollo
    restart: unless-stopped
    working_dir: /app/front
    command: npm run dev:docker
    env_file:
      - ./front/.env.docker
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app/front
      - front_node_modules:/app/front/node_modules
    depends_on:
      back-reservas-desarrollo:
        condition: service_started
    networks:
      - reservas-network
      
  front-reservas-produccion:
    build:
      context: .
      dockerfile: front/Dockerfile.prod  
    container_name: front-reservas-produccion
    restart: unless-stopped
    ports:
      - "8081:80"
    env_file:
      - ./front/.env.docker
    depends_on:
      back-reservas-desarrollo:
        condition: service_started
    networks:
    - reservas-network


volumes:
  db_data:
  back_node_modules:
  back_logs:
  back_uploads:
  front_node_modules:

networks:
  reservas-network:
    driver: bridge
